export const CART_ACTION_TYPES = {
    ADD_TO_CART :"cart/ADD_TO_CART",
    REMOVE_FROM_CART : "cart/REMOVE_FROM_CART",
    INCREMENT_ITEM_COUNT : "cart/INCREMENT_ITEM_COUNT",
    DECREMENT_ITEM_COUNT : "cart/DECREMENT_ITEM_COUNT",
    SET_IS_CART_OPEN : "cart/SET_IS_CART_OPEN",
    SET_CART_ITEMS : "cart/SET_CART_ITEMS",
    TOTOAL_ITEMS_IN_CART : "cart/TOTAL_ITEMS"
}